// transcoder.proto is the wire contract between the main open-streamer
// process and a per-stream open-streamer-transcoder subprocess.
//
// One Unix-domain socket per stream. The supervisor in
// internal/transcoder/service.go opens a bidi stream and pushes raw
// ingest TS bytes + control messages; the subprocess returns encoded
// MPEG-TS chunks per rendition + health / error events.
//
// Single bidi stream (not unary RPCs) so a missed packet on the wire
// kills the stream and the supervisor respawns the subprocess — keeps
// failure semantics identical to crash recovery.
//
// P0 SCOPE: contract sketch only. Code generation (protoc → .pb.go) is
// deferred to P4 when the gRPC supervisor lands. Until then the file
// documents the intended wire layout for review.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.0
// source: internal/transcoder/native/proto/transcoder.proto

package transcoderpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Transcoder_Run_FullMethodName = "/transcoder.v1.Transcoder/Run"
)

// TranscoderClient is the client API for Transcoder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TranscoderClient interface {
	// Run is the per-stream bidi stream. The supervisor sends ConfigureRequest
	// first (always), then a stream of InputPacket / SwitchInput / Stop
	// messages; the subprocess streams back OutputPacket / Health / Error
	// until the stream ends or an Error with terminal=true arrives.
	Run(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Event], error)
}

type transcoderClient struct {
	cc grpc.ClientConnInterface
}

func NewTranscoderClient(cc grpc.ClientConnInterface) TranscoderClient {
	return &transcoderClient{cc}
}

func (c *transcoderClient) Run(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Transcoder_ServiceDesc.Streams[0], Transcoder_Run_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Event]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Transcoder_RunClient = grpc.BidiStreamingClient[Request, Event]

// TranscoderServer is the server API for Transcoder service.
// All implementations must embed UnimplementedTranscoderServer
// for forward compatibility.
type TranscoderServer interface {
	// Run is the per-stream bidi stream. The supervisor sends ConfigureRequest
	// first (always), then a stream of InputPacket / SwitchInput / Stop
	// messages; the subprocess streams back OutputPacket / Health / Error
	// until the stream ends or an Error with terminal=true arrives.
	Run(grpc.BidiStreamingServer[Request, Event]) error
	mustEmbedUnimplementedTranscoderServer()
}

// UnimplementedTranscoderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTranscoderServer struct{}

func (UnimplementedTranscoderServer) Run(grpc.BidiStreamingServer[Request, Event]) error {
	return status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedTranscoderServer) mustEmbedUnimplementedTranscoderServer() {}
func (UnimplementedTranscoderServer) testEmbeddedByValue()                    {}

// UnsafeTranscoderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranscoderServer will
// result in compilation errors.
type UnsafeTranscoderServer interface {
	mustEmbedUnimplementedTranscoderServer()
}

func RegisterTranscoderServer(s grpc.ServiceRegistrar, srv TranscoderServer) {
	// If the following call panics, it indicates UnimplementedTranscoderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Transcoder_ServiceDesc, srv)
}

func _Transcoder_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TranscoderServer).Run(&grpc.GenericServerStream[Request, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Transcoder_RunServer = grpc.BidiStreamingServer[Request, Event]

// Transcoder_ServiceDesc is the grpc.ServiceDesc for Transcoder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Transcoder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transcoder.v1.Transcoder",
	HandlerType: (*TranscoderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _Transcoder_Run_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/transcoder/native/proto/transcoder.proto",
}
